steps:
- name: 'python:3.8'
  entrypoint: python3
  args: ['-m', 'venv', 'venv']
- name: 'python:3.8'
  entrypoint: 'venv/bin/pip'
  args: ['install', '-V', '-r', 'requirements.txt']
- name: 'python:3.8'
  #entrypoint: python3
  entrypoint: 'venv/bin/python'
  args: ['./manage.py', 'collectstatic', '--noinput']
  env:
    - 'SECRET_KEY=${_SECRET_KEY}'
    - 'WEATHER_API_KEY=${_WEATHER_API_KEY}'
  #secretEnv: ['SECRET_KEY']
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
timeout: "1600s"

#availableSecrets:
#  secretManager:
#  ***REMOVED***
#    env: 'SECRET_KEY'
    #env: 'WEATHER_API_KEY'