name: AQI Forecast (Django + React.js) CI/CD
run-name: 
on: [push]
jobs:
  activate_venv:
    name: Activate virtual environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Activate venv
        run: . venv/bin/activate
  test_react:
    name: Run React tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test React
        run: npm run test --prefix frontend